name: lara
description: "Lara projetc"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  package_info_plus: ^9.0.0
  firebase_crashlytics: ^5.0.7
  firebase_core: ^4.4.0
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2
  firebase_auth: ^6.1.4
  equatable: ^2.0.8
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.4
  dartz: ^0.10.1
  cloud_firestore: ^6.1.2
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^1.6.0
  uuid: ^4.5.3
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_24pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_24pt-BoldItalic.ttf
          weight: 700
          style: italic
